ProyectoItineris/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from ProyectoItineris import settings

urlpatterns = [
    path('', include("itineris.urls")),
    path('admin/', admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('select2/', include("django_select2.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

itineris/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("work_with_us", views.work_with_us, name="work_with_us"),
    path("about_us", views.about, name="about_us"),
    path("create_travel", views.create_travel, name="create_travel"),
    path("show_waypoints", views.show_waypoints, name="show_waypoints"),
    path("add_waypoint", views.add_waypoint, name="add_waypoint"),
    path("delete_waypoint/<str:waypoint_id>/", views.delete_waypoint, name="delete_waypoint"),
    path("show_segments/", views.show_segments, name="show_segments"),
    path("generate_segments/", views.generate_segments, name="generate_segments"),
    path("end_travel_creation/", views.end_travel_creation, name="end_travel_creation"),
    path("get_available_options", views.get_available_options, name="get_available_options"),
    path("travel_result", views.travel_result, name="travel_result"),
    path("travel_result_failed", views.travel_result_failed, name="travel_result_failed"),
    path("show_travelers", views.show_travelers, name="show_travelers"),
    path("pre_checkout/<str:segment_id>/", views.pre_checkout, name="pre_checkout"),
    path("your_drivers", views.your_drivers, name="your_drivers"),
    path("delete_driver/<str:driver_id>/", views.delete_driver, name="delete_driver"),
    path("update_driver/<str:driver_id>/", views.update_driver, name="update_driver"),
    path("your_travels", views.your_travels, name="your_travels"),
    path("travel_detail/<str:travel_id>/", views.travel_detail, name="travel_detail"),
    path("mark_travel_ended/<str:travel_id>/", views.mark_travel_ended, name="mark_travel_ended"),
    path("start_trip/<str:travel_id>/", views.start_trip, name="start_trip"),
    path("your_vehicles", views.your_vehicles, name="your_vehicles"),
    path("delete_vehicle/<str:plate_number>/", views.delete_vehicle, name="delete_vehicle"),
    path("update_vehicle/<str:plate_number>/", views.update_vehicle, name="update_vehicle"),
    path("checkout", views.checkout, name="checkout"),
    path("travel_history", views.travel_history, name="travel_history"),
    path("export_travel_history", views.export_travel_history, name="export_travel_history"),
    path("payment_success", views.payment_success, name="payment_success"),
    path("feedback/<str:encrypted_traveler_id>/", views.feedback, name="feedback"),
    path("update_feedback/", views.update_feedback, name="update_feedback"),
    path("update_traveler/<str:encrypted_traveler_id>/", views.update_traveler, name="update_traveler"),
    path("cancel_traveler_ticket/<str:encrypted_traveler_id>/", views.cancel_traveler_ticket,
         name="cancel_traveler_ticket"),
    path("update_travel/<str:travel_id>/", views.update_travel, name="update_travel"),
    path("export_travelers_to_csv/<str:travel_id>/", views.export_travelers_to_csv, name="export_travelers_to_csv"),
]

members/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login_user', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path("sign_up_business", views.sign_up_business, name="sign_up_business"),
]

itineris/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from django.forms import modelformset_factory

from .models import Company, Vehicle, Driver, Travel, Traveler, Period, Weekday, Segment, City, Waypoint, Nationality

from django import forms
from django_select2 import forms as s2forms


def validate_positive(value):
    if value <= 0:
        raise ValidationError('Debe ingresar un numero mayor que cero')


class CompanyCreationForm(UserCreationForm):
    class Meta:
        model = Company
        fields = ('username', 'email')


class CompanyChangeForm(UserChangeForm):
    class Meta:
        model = Company
        fields = ('username', 'email')



class CreateTravel(forms.Form):
    city_origin = forms.ModelChoiceField(queryset=City.objects.all().order_by('city_name'),
                                         label='Ciudad de salida',
                                         widget=s2forms.ModelSelect2Widget(
                                             model=City, search_fields=['city_name__icontains'],
                                         )
                                         )
    city_destination = forms.ModelChoiceField(queryset=City.objects.all().order_by('city_name'),
                                              label='Ciudad de destino',
                                              widget=s2forms.ModelSelect2Widget(model=City,
                                                                                search_fields=['city_name__icontains'],
                                                                                )
                                              )
    datetime_departure = forms.DateTimeField(label='Fecha y hora de salida',
                                             widget=forms.widgets.DateTimeInput(attrs={'type': 'datetime-local'}),
                                             required=True)
    datetime_arrival = forms.DateTimeField(label='Fecha y hora estimada de llegada',
                                           widget=forms.widgets.DateTimeInput(attrs={'type': 'datetime-local'}),
                                           required=True)
    address = forms.CharField(label='Dirección de salida', max_length=200, widget=forms.TextInput(attrs={
        'id': 'autocomplete',  # ID necesario para el autocompletado
        'placeholder': 'Ingresa una dirección',
    }))
    geocode = forms.CharField(max_length=100, required=False)
    driver = forms.ModelChoiceField(queryset=Driver.objects.none(), required=True)
    vehicle = forms.ModelChoiceField(queryset=Vehicle.objects.none(), required=True)

    def __init__(self, company_id, *args, **kwargs):
        super(CreateTravel, self).__init__(*args, **kwargs)
        self.fields['city_origin'].widget.attrs['class'] = 'form-control'
        self.fields['city_destination'].widget.attrs['class'] = 'form-control'
        self.fields['datetime_departure'].widget.attrs['class'] = 'form-control'
        self.fields['datetime_arrival'].widget.attrs['class'] = 'form-control'
        self.fields['driver'] = forms.ModelChoiceField(label='Conductor', queryset=Driver.objects.filter(company_id=company_id,
                                                                                      active=1))
        self.fields['driver'].widget.attrs['class'] = 'form-control'
        self.fields['vehicle'] = forms.ModelChoiceField(label='Vehículo', queryset=Vehicle.objects.filter(company_id=company_id,
                                                                                        status='Disponible',
                                                                                        active=1))
        self.fields['vehicle'].widget.attrs['class'] = 'form-control'
        self.fields['geocode'].widget = forms.HiddenInput()


class CreateWaypoint(forms.ModelForm):
    city = forms.ModelChoiceField(queryset=City.objects.all().order_by('city_name'),
                                  label='Ciudad de destino',
                                  widget=s2forms.ModelSelect2Widget(model=City,
                                                                    search_fields=['city_name__icontains'],
                                                                    )
                                  )
    estimated_datetime_arrival = forms.DateTimeField(label='Fecha y hora de salida',
                                                     widget=forms.widgets.DateTimeInput(
                                                         attrs={'type': 'datetime-local'}),
                                                     )

    class Meta:
        model = Waypoint
        fields = ['city', 'estimated_datetime_arrival']

    def __init__(self, *args, **kwargs):
        super(CreateWaypoint, self).__init__(*args, **kwargs)
        self.fields['city'].widget.attrs['class'] = 'form-control'
        self.fields['estimated_datetime_arrival'].widget.attrs['class'] = 'form-control'


class EditSegment(forms.ModelForm):
    waypoint_origin = forms.ModelChoiceField(queryset=Waypoint.objects.all(), label='Ciudad de origen')
    waypoint_destination = forms.ModelChoiceField(queryset=Waypoint.objects.all(), label='Ciudad de destino')
    origin_display = forms.CharField()
    destination_display = forms.CharField()
    fee = forms.IntegerField(label='Tarifa', step_size=100)

    class Meta:
        model = Segment
        fields = ['waypoint_origin', 'waypoint_destination', 'origin_display', 'destination_display', 'fee']

    def __init__(self, *args, **kwargs):
        super(EditSegment, self).__init__(*args, **kwargs)
        self.fields['fee'].widget.attrs['class'] = 'form-control'
        self.fields['fee'].widget.attrs['style'] = 'width:120px'

        # Se esconden los campos verdaderos de la instancia
        self.fields['waypoint_origin'].widget = forms.HiddenInput()
        self.fields['waypoint_destination'].widget = forms.HiddenInput()

        # Mostrar los valores como texto no editable
        self.fields['origin_display'] = forms.CharField(
            initial=self.instance.waypoint_origin.city,
            label='Ciudad de origen',
            widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'})
        )
        self.fields['destination_display'] = forms.CharField(
            initial=self.instance.waypoint_destination.city,
            label='Ciudad de destino',
            widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'})
        )


EditSegmentFormSet = modelformset_factory(Segment, form=EditSegment, extra=0)

class PeriodTravel(forms.ModelForm):
    weekdays = forms.ModelMultipleChoiceField(label="Dia de la semana", queryset=Weekday.objects.all(),
                                              widget=s2forms.ModelSelect2MultipleWidget(
                                                  model=Weekday, search_fields=['weekday__icontains'],
                                                  attrs={'data-minimum-input-length': 0}),
                                              required=False)

    end_date = forms.DateField(label='Fin del periodo', widget=forms.widgets.DateInput(
        attrs={'type': 'date', 'id': 'period_end_date'}), required=False)

    class Meta:
        model = Period
        fields = ('weekdays', 'end_date',)

    def __init__(self, *args, **kwargs):
        super(PeriodTravel, self).__init__(*args, **kwargs)
        self.fields['weekdays'].widget.attrs['class'] = 'form-control'
        self.fields['end_date'].widget.attrs['class'] = 'form-control'


class CreateVehicle(forms.ModelForm):
    plate_number = forms.CharField(label='Patente', max_length=20, required=True)
    brand = forms.CharField(label='Marca', max_length=100)
    car_model = forms.CharField(label='Modelo', max_length=100)
    capacity = forms.IntegerField(label='Capacidad', validators=[validate_positive])
    color = forms.CharField(label='Color', required=False)

    class Meta:
        model = Vehicle
        fields = ('plate_number', 'brand', 'car_model', 'capacity', 'color',)

    def __init__(self, *args, disable_plate=False, **kwargs):
        super(CreateVehicle, self).__init__(*args, **kwargs)
        self.fields['plate_number'].widget.attrs['class'] = 'form-control'
        self.fields['brand'].widget.attrs['class'] = 'form-control'
        self.fields['car_model'].widget.attrs['class'] = 'form-control'
        self.fields['capacity'].widget.attrs['class'] = 'form-control'
        self.fields['color'].widget.attrs['class'] = 'form-control'

        if disable_plate:
            self.fields['plate_number'].disabled = True
            self.fields['plate_number'].widget.attrs['title'] = 'No se puede modificar la patente. Agrega otro vehiculo de ser necesario.'


class CreateDriver(forms.ModelForm):
    first_name = forms.CharField(label='Nombre', max_length=100, required=True)
    last_name = forms.CharField(label='Apellido', max_length=100, required=True)
    license_number = forms.CharField(label='Número de licencia', max_length=100, required=True)
    email = forms.EmailField(label='Email', max_length=100)
    phone_number = forms.CharField(label='Teléfono', max_length=100)

    class Meta:
        model = Driver
        fields = ('first_name', 'last_name', 'license_number', 'email', 'phone_number',)

    def __init__(self, *args, **kwargs):
        super(CreateDriver, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['license_number'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['phone_number'].widget.attrs['class'] = 'form-control'


class SearchTravel(forms.Form):
    NUMBER_CHOICES = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]

itineris/templates/itineris/checkout.html
{% extends 'itineris/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            {% for traveler in travelers %}
                <div class="card mb-4" style="width: 35rem;">
                    <div class="row g-0">
                        <div class="col-md-1 rounded-start" style=" background: #1169bb">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body fw-bold">
                                <p>Nombre: {{ traveler.first_name }} {{ traveler.last_name }}</p>
                                <p>DNI: {{ traveler.dni }}</p>
                                <p>Mail: {{ traveler.email }}</p>
                                <p>Tel: {{ traveler.phone }}</p>
                                <p>Origen: {{ traveler.address_origin }}</p>
                                <p>Destino: {{ traveler.address_destination }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col mt-5"><div id="wallet_container">
            </div>
        </div>
    </div>
</div>
    
<script>
    const mp = new MercadoPago('APP_USR-9f3337f7-63a3-4b00-aeb8-217693ccc7cd', {
        locale: 'es-AR'
        });

    mp.bricks().create("wallet", "wallet_container", {
        initialization: {
            preferenceId: "{{ preference.id }}",
        },
    });

</script>

{% endblock %}

itineris/templates/itineris/feedback.html
{% extends 'itineris/base.html' %}

{% block content %}
    <div class="container text-center">
        <form action="{% url 'update_feedback' %}" method=POST>
            {% csrf_token %}
            <div class="mb-3">
                <label for="feedback" class="form-label display-1 mb-2">Dejanos una reseña</label>
                <input hidden="hidden" id="traveler_id" name="traveler_id" value="{{ traveler.id }}">
                <input type="text" class="form-control" id="feedback" name="feedback" aria-describedby="feedbackHelp">
                <div id="feedbackHelp" class="form-text">Resalta si tuviste una buena experiencia o si tuviste algún inconveniente.</div>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
{% endblock %}

itineris/templates/itineris/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>footer</title>
</head>
<body>
<section class="footer">
    <h4>Sobre nosotros</h4>
    <p>lorem ipsum</p>
    <div class="icons">
        <i class="fa fa-facebook"></i>
        <i class="fa fa-twitter"></i>
        <i class="fa fa-instagram"></i>
    </div>
</section>
</body>
</html>

itineris/templates/itineris/index.html
{% extends 'itineris/base.html' %}

{% block content %}
    <br>
<div class="container">
    <div class="row">
            <h1>¿A dónde querés ir?</h1>
    </div>
    <div class="row">
        <div class="travel-col">
            <form action="{% url 'index' %}" method=POST>
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Buscar" class="btn btn-primary">
            </form>

        </div>
    </div>
   </div>
    <script>
    function getCurrentDate() {
        const now = new Date();
        const year = now.getFullYear();
        const month = String(now.getMonth() + 1).padStart(2, '0'); // Months are zero-indexed
        const day = String(now.getDate()).padStart(2, '0');

        return `${year}-${month}-${day}`;
    }
    document.addEventListener('DOMContentLoaded', function() {
        const datetime_departure = document.querySelector('#id_datetime_departure');
        
        datetime_departure.setAttribute('min', getCurrentDate());
    });
    
        
    </script>
{% endblock %}

itineris/templates/itineris/navbar-business.html
{% load static %}

<nav class="sidebar">
    <div class="sd-header">
        <div class="image-text">
                <span class="image">
                    <img src="{% static 'itineris/images/logo_reducido.png' %}" alt="logo">
                </span>

            <div class="text header-text">
                    <span class="business">
                        <b>{{ user.company_name }}</b>
                    </span>
            </div>
            <div>
                <i class='bi bi-chevron-right toggle'></i>
            </div>
        </div>
    </div>

    <div class="menu-bar">
        <div class="menu">
            <ul class="menu-links">
                <li class="sb-nav-link ">
                    <a href="{% url 'create_travel' %}">
                        <i class='bi bi-calendar-plus icon'></i>
                        <span class="text sb-nav-text">Crear viaje</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'your_travels' %}">
                        <i class='bi bi-signpost-split icon'></i>
                        <span class="text sb-nav-text">Viajes</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'your_vehicles' %}">
                        <i class='bi bi-bus-front icon'></i>
                        <span class="text sb-nav-text">Vehículos</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'your_drivers' %}">
                        <i class='bi bi-person icon'></i>
                        <span class="text sb-nav-text">Conductores</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'travel_history' %}">
                        <i class="bi bi-clock-history icon"></i>
                        <span class="text sb-nav-text">Historial</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'logout' %}">
                        <i class='bi bi-box-arrow-left icon'></i>
                        <span class="text sb-nav-text">Salir</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!---------------- JavaScript to toggle the menu ----------------------->
<script>
    const body = document.querySelector("body"),
        sidebar = body.querySelector(".sidebar"),
        toggle = sidebar.querySelector(".toggle");

    toggle.addEventListener("click", () => {
        sidebar.classList.toggle("close");
    })
</script>

itineris/templates/itineris/navbar.html
{% load static %}

<nav class="navbar sticky-top navbar-expand-md bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand d-flex align-items-center" href="{% url 'index' %}">
            <img src="{% static 'itineris/images/itineris_icon_48px.png' %}" alt="Logo" height="48"
                 class="d-inline-block align-text-top">
            <span class="ml-2">ITINERIS</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sign_up_business' %}">EMPRESAS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'work_with_us' %}">TRABAJA CON NOSOTROS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about_us' %}">SOBRE NOSOTROS</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-secondary me-2 nav-button" type="button" href="{% url 'logout' %}">CERRAR
                        SESION</a>
                {% else %}
                    <a class="btn btn-outline-secondary me-2 nav-button" type="button" href="{% url 'login' %}">INICIAR
                        SESION</a>
                {% endif %}
            </form>
        </div>
    </div>
</nav>

<div class="container">
    <br>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
</div>

itineris/templates/itineris/navbar_business.html
{% load static %}

<nav class="sidebar">
    <div class="sd-header">
        <div class="image-text">
                <span class="image">
                    <img src="{% static 'itineris/images/logo_reducido.png' %}" alt="logo">
                </span>

            <div class="text header-text">
                    <span class="business">
                        <b>{{ user.company_name }}</b>
                    </span>
            </div>
            <div>
                <i class='bi bi-chevron-right toggle'></i>
            </div>
        </div>
    </div>
    
    <div class="menu-bar">
        <div class="menu">
            <ul class="menu-links">
                <li class="sb-nav-link ">
                    <a href="{% url 'create_travel' %}">
                        <i class='bi bi-calendar-plus icon'></i>
                        <span class="text sb-nav-text">Crear viaje</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'your_travels' %}">
                        <i class='bi bi-signpost-split icon'></i>
                        <span class="text sb-nav-text">Viajes</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'your_vehicles' %}">
                        <i class='bi bi-bus-front icon'></i>
                        <span class="text sb-nav-text">Vehículos</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'your_drivers' %}">
                        <i class='bi bi-person icon'></i>
                        <span class="text sb-nav-text">Conductores</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'travel_history' %}">
                        <i class="bi bi-clock-history icon"></i>
                        <span class="text sb-nav-text">Historial</span>
                    </a>
                </li>
                <li class="sb-nav-link">
                    <a href="{% url 'logout' %}">
                        <i class='bi bi-box-arrow-left icon'></i>
                        <span class="text sb-nav-text">Salir</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="container">
    <br>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</nav>

<!---------------- JavaScript to toggle the menu ----------------------->
<script>
    const body = document.querySelector("body"),
        sidebar = body.querySelector(".sidebar"),
        toggle = sidebar.querySelector(".toggle");

    toggle.addEventListener("click", () => {
        sidebar.classList.toggle("close");
    })
</script>

itineris/templates/itineris/travel_result.html
{% extends 'itineris/base.html' %}

{% load mathfilters %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% for segment in segments %}
                <div class="card text-center mb-4">
                    <div class="card-header">
                        <h3 class="fw-bold">{{ segment.travel.company.company_name }}</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
    
                            </div>
                            <div class="col-md-2">
                                <p class="fw-bold">{{ segment.waypoint_origin.city }}</p>
                                <p>{{ segment.waypoint_origin.estimated_datetime_arrival }}</p>
                            </div>
                            <div class="col-md-2">
                                <p>Tiempo de viaje</p>
                                <p>{{ segment.duration }}</p>
                            </div>
                            <div class="col-md-2">
                                <p class="fw-bold">{{ segment.waypoint_destination.city }}</p>
                                <p>{{ segment.waypoint_destination.estimated_datetime_arrival }}</p>
                            </div>
                            <div class="col-md-3">
                                <a href="{% url 'pre_checkout' segment.id%}">
                                    <button type="button" class="btn btn-primary">${{ segment.fee|floatformat }}</button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-body-secondary">
                        Quedan {{ segment.seats_available }} lugares disponibles
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

    <!---------------- JavaScript to toggle the menu ----------------------->
    <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }

        function hideMenu(){
            navLinks.style.right = "-200px";
        }


    </script>
{% endblock %}

itineris/templates/itineris/travel_result_failed.html
{% extends 'itineris/base.html' %}
{% load static %}

<title>Viajes</title>
{% block content %}
<div class="container-fluid vh-100 pt-4" style="background-color: #79bcd7; margin-top: -24px;">
    <div class="row">
        <div class="col text-center">
            <h1 class="fw-bolder">¡No se encontraron viajes!</h1>
            <img src="{% static 'itineris/images/travel_result_failed.jpeg' %}" alt="Success image" style="width: inherit">
        </div>
    </div>
</div>
{% endblock %}

itineris/templates/itineris/update_driver.html
{% extends 'itineris/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3 mx-auto mt-3">
            <div class="card m-4 p-3">
                <h2>Edita tu conductor:</h2> <h3 class="text-muted">{{ driver }}</h3>
                <form action="{% url 'update_driver' driver.driver_id %}" method=POST>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <button type="submit" class="btn btn-success me-auto p-2 fs-4 mb-2">Guardar cambios</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

itineris/templates/itineris/update_vehicle.html
{% extends 'itineris/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3 mx-auto mt-3">
            <div class="card m-4 p-3">
                <h2>Edita tu vehiculo:</h2> <h3 class="text-muted">{{ vehicle }}</h3>
                <form action="{% url 'update_vehicle' vehicle.plate_number %}" method=POST>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <button type="submit" class="btn btn-success me-auto p-2 fs-4 mb-2">Guardar cambios</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}